version: '3.7'

services:
  api:
    depends_on:
      - db
    build: .
    container_name: api
    restart: always
    env_file: .env
    ports:
      - 8080:8080
  db:
    container_name: db
    image: mongo:latest
    restart: always
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
